# Generated by Django 2.2.5 on 2023-10-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231028_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.Categoty', verbose_name='دسته بندی'),
        ),
    ]
